interface Env {
  WEB3_ENDPOINT_MAP: string;
  METADATA_SERVICE_WEBHOOK_SECRET?: string;
  LOCALHOST_ENS_REGISTRY?: string;
  LOCALHOST_ENS_NAME_WRAPPER?: string;
  LOCALHOST_ENS_UNIVERSAL_RESOLVER?: string;
  LOCALHOST_ENS_PUBLIC_RESOLVER?: string;
  LOCALHOST_ENS_BASE_REGISTRAR_IMPLEMENTATION?: string;
  LOCALHOST_ENS_ETH_REGISTRAR_CONTROLLER?: string;
  LOCALHOST_ENS_REVERSE_REGISTRAR?: string;
  LOCALHOST_MULTICALL3?: string;
}
